### ISSUE TITLE
Leading minus signs throw ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by henryfailbetter** [MathosProject/Mathos-Parser#21]
Hi, I had a problem with the parser where expressions with leading minus signs threw an out of range exception. Apologies if this format is not supported.

The expression in question was "-(3+2+1+6)/4".

`System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List1.get_Item(Int32 index)
   at Mathos.Parser.MathParser.BasicArithmeticalExpression(List1 tokens)
   at Mathos.Parser.MathParser.MathParserLogic(List1 tokens)
   at Mathos.Parser.MathParser.Parse(String mathExpression)
   at ...`

**Comment by napen123** [comment]
This should be fixed by #23 (courtesy of @dennisvg111).
